export const refs = {
    body: document.querySelector('body'),
    categoriesList: document.querySelector('.categories'),
    productsList: document.querySelector('.products'),
    divNotFound: document.querySelector('.not-found'),
    loadMoreBtn: document.querySelector('.load-more-btn'),
    searchForm: document.querySelector('.search-form'),
    formBtnClearValue: document.querySelector('.search-form__btn-clear'),
    modal: document.querySelector('.modal'),
    modalProduct: document.querySelector('.modal-product'),
    modalCloseBtn: document.querySelector('.modal__close-btn'),
    modalWishlistBtn: document.querySelector('.modal-product__btn--wishlist'),
    modalCartBtn: document.querySelector('.modal-product__btn--cart'),
    navCountWishlist: document.querySelector('[data-wishlist-count]'),
    navCountCart: document.querySelector('[data-cart-count]'),
    sidebarCountCart: document.querySelector('[data-count]'),
    sidebarPriceCart: document.querySelector('[data-price]'),
    buyProductsBtn: document.querySelector('.cart-summary__btn'),
    loader: document.querySelector('.loader'),
    scrollTopBtn: document.querySelector('.scroll-top-btn'),
    themeToggleBtn: document.querySelector('.theme-toggle-btn'),
}